version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - OPENAI_VERSION=${OPENAI_VERSION}
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped